apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: {{ .Values.backend.syncFiles }}
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-rendered-patterns
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: {{ .Values.backend.renderedPatterns }}
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
